const images = {
  abdominaux: {
    crunchpoulie: require("../assets/abdos/crunchpoulie.gif"),
    planche: require("../assets/abdos/planche.gif"),
    relevegenoux: require("../assets/abdos/relevegenoux.gif"),
    roulette: require("../assets/abdos/roulette.gif"),
    crunchSol: require("../assets/abdos/crunchSol.gif"),
    relevesGenouxChaiseRomaine: require("../assets/abdos/relevesGenouxChaiseRomaine.gif"),
    plancheLaterale: require("../assets/abdos/plancheLaterale.gif"),
    mountainClimber: require("../assets/abdos/mountainClimber.gif"),
    crunchMachine: require("../assets/abdos/crunchMachine.gif"),
    flexionLatHalteres: require("../assets/abdos/flexionLatHalteres.gif"),
    ciseaux: require("../assets/abdos/ciseaux.gif"),
  },
  biceps: {
    curl: require("../assets/biceps/curl.gif"),
    curlmarteau: require("../assets/biceps/curlmarteau.gif"),
    curlpoulie: require("../assets/biceps/curlpoulie.gif"),
    curlpupitre: require("../assets/biceps/curlpupitre.gif"),
    curlBarre: require("../assets/biceps/curlBarre.gif"),
    curlConcentre: require("../assets/biceps/curlConcentre.gif"),
    curlPupitreEz: require("../assets/biceps/curlPupitreEz.gif"),
    curlMachine: require("../assets/biceps/curlMachine.gif"),
    curlInclineRotation: require("../assets/biceps/curlInclineRotation.gif"),
    curlPoulieVisAVis: require("../assets/biceps/curlPoulieVisAVis.gif"),
  },
  cardio: {
    rameur: require("../assets/cardio/rameur.gif"),
    tapis: require("../assets/cardio/tapis.gif"),
    velo: require("../assets/cardio/velo.gif"),
    veloelliptique: require("../assets/cardio/veloelliptique.gif"),
    assaultBike: require("../assets/cardio/assaultBike.gif"),
    escaliers: require("../assets/cardio/escaliers.gif"),
  },
  dos: {
    rowingbarre: require("../assets/dos/rowingbarre.gif"),
    tiragehorizontal: require("../assets/dos/tiragehorizontal.gif"),
    tiragevertical: require("../assets/dos/tiragevertical.gif"),
    traction: require("../assets/dos/traction.gif"),
    tractionSuppination: require("../assets/dos/tractionSuppination.gif"),
    rowingHaltere: require("../assets/dos/rowingHaltere.gif"),
    tirageVerticalMachine: require("../assets/dos/tirageVerticalMachine.gif"),
    rowingMachine: require("../assets/dos/rowingMachine.gif"),
    tirageVerticalMachine: require("../assets/dos/tirageVerticalMachine.gif"),
    pullOverPoulie: require("../assets/dos/pullOverPoulie.gif"),
    tirageVerticalPriseInversee: require("../assets/dos/tirageVerticalPriseInversee.gif"),
  },
  épaules: {
    developpemilitaire: require("../assets/epaules/developpemilitaire.gif"),
    elevationsfrontales: require("../assets/epaules/elevationsfrontales.gif"),
    elevationslaterales: require("../assets/epaules/elevationslaterales.gif"),
    facepull: require("../assets/epaules/facepull.gif"),
    developpeArnold: require("../assets/epaules/developpeArnold.gif"),
    developpeEpaulesHalteres: require("../assets/epaules/developpeEpaulesHalteres.gif"),
    elevationLateralesHalteres: require("../assets/epaules/elevationLateralesHalteres.gif"),
    oiseauBanc: require("../assets/epaules/oiseauBanc.gif"),
    elevationLateralesPoulie: require("../assets/epaules/elevationLateralesPoulie.gif"),
  },
  fessiers: {
    fentes: require("../assets/fessiers/fentes.gif"),
    hipthrust: require("../assets/fessiers/hipthrust.gif"),
    kettlebellswing: require("../assets/fessiers/kettlebellswing.gif"),
    reversehyperextension: require("../assets/fessiers/reversehyperextension.gif"),
    squat: require("../assets/fessiers/squat.gif"),
    monteeBanc: require("../assets/fessiers/monteeBanc.gif"),
    extensionsPoulieBasse: require("../assets/fessiers/extensionsPoulieBasse.gif"),
  },
  ischio: {
    fente: require("../assets/ischio/fente.gif"),
    legcurl: require("../assets/ischio/legcurl.gif"),
    soulevedeterre: require("../assets/ischio/soulevedeterre.gif"),
    soulevedeterresumo: require("../assets/ischio/soulevedeterresumo.gif"),
    frontSquatHalteres: require("../assets/ischio/frontSquatHalteres.gif"),
    legCurlAssisMachine: require("../assets/ischio/legCurlAssisMachine.gif"),
    presseCuisseIncline: require("../assets/ischio/presseCuisseIncline.gif"),
  },
  pectoraux: {
    butterfly: require("../assets/pectoraux/butterfly.gif"),
    developpecouchehalteres: require("../assets/pectoraux/developpecouchehalteres.gif"),
    developpeincline: require("../assets/pectoraux/developpeincline.gif"),
    ecartepoulie: require("../assets/pectoraux/ecartepoulie.gif"),
    developpeCouche: require("../assets/pectoraux/developpecouche.gif"),
    ecarteCoucheHaltere: require("../assets/pectoraux/ecarteCoucheHaltere.gif"),
    developpeInclineMachineConvergente: require("../assets/pectoraux/developpeInclineMachineConvergente.gif"),
    developpeDeclineBarre: require("../assets/pectoraux/developpeDeclineBarre.gif"),
    pullover: require("../assets/pectoraux/pullover.gif"),
    developpeCoucheSmithMachine: require("../assets/pectoraux/developpeCoucheSmithMachine.gif"),
    ecartePoulieVisAVisHaute: require("../assets/pectoraux/ecartePoulieVisAVisHaute.gif"),
    developpeInclinePoulie: require("../assets/pectoraux/developpeInclinePoulie.gif"),
    developpeMachineAssisPectoraux: require("../assets/pectoraux/developpeMachineAssisPectoraux.gif"),
    ecartesInclineAvecHalteres: require("../assets/pectoraux/ecartesInclineAvecHalteres.gif"),
    developpeInclineHalteres: require("../assets/pectoraux/developpeInclineHalteres.gif"),
    ecartesPoulieVisAVis: require("../assets/pectoraux/ecartesPoulieVisAVis.gif"),
    ecarteUnilateralALlaPoulie: require("../assets/pectoraux/ecarteUnilateralALlaPoulie.gif"),
  },
  quadriceps: {
    hacksquat: require("../assets/quadriceps/hacksquat.gif"),
    legextension: require("../assets/quadriceps/legextension.gif"),
    press: require("../assets/quadriceps/press.gif"),
    squat: require("../assets/quadriceps/squat.gif"),
    presseCuisseCote: require("../assets/quadriceps/presseCuisseCote.gif"),
    fentesKettleBell: require("../assets/quadriceps/fentesKettleBell.gif"),
    presseHorizontale: require("../assets/quadriceps/presseHorizontale.gif"),
  },
  triceps: {
    dips: require("../assets/triceps/dips.gif"),
    extensionhalteres: require("../assets/triceps/extensionhalteres.gif"),
    extensiontriceps: require("../assets/triceps/extensiontriceps.gif"),
    extensiontricepscorde: require("../assets/triceps/extensiontricepscorde.gif"),
    barreFront: require("../assets/triceps/barreFront.gif"),
    extensionMachine: require("../assets/triceps/extensionMachine.gif"),
    extensionAssis: require("../assets/triceps/extensionAssis.gif"),
    extensionVerticalPoulieBasse: require("../assets/triceps/extensionVerticalPoulieBasse.gif"),
    dipsBanc: require("../assets/triceps/dipsBanc.gif"),
  },
};

export default images;
